title: VOCAL
description: Documentation et supports de formation du plugin QGIS VOCAL
remote_theme: just-the-docs/just-the-docs

url: https://aurell-aermc.github.io
baseurl: /Le-VOCAL

search_enabled: true