title: VOCAL
description: Documentation et supports de formation du plugin QGIS VOCAL

url: https://aurell-aermc.github.io
baseurl: /Le-VOCAL

theme: just-the-docs

search_enabled: true
heading_anchors: true

back_to_top: true
back_to_top_text: "Retour en haut"

color_scheme: light
